name: qr_mobile_vision_example
description: Demonstrates how to use the qr_mobile_vision plugin.

version: 1.0.0+0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.25.0-8.1.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  qr_mobile_vision:
    path: ../

flutter:
  uses-material-design: true